"""Shared constants and utilities for pre-handoff checks.

Constants split rule:
  - Things used by *multiple* topic-modules live here (WHITELIST,
    CRITERIA_FRONTMATTER_REQUIRED).
  - Things used by exactly one topic module live in that module
    (REQUIRED_HANDOFF_SECTIONS -> handoff.py, OPTIONAL_VALIDATORS -> validators.py, ...).
  - TIER_CHECKS stays in handoff-precheck.py (dispatch concern, not check concern).

Utilities here:
  - read_criteria_meta(eng): read size / ux_heavy / domain / engagement from
    criteria.md frontmatter. Returns {} on missing or unparseable.
  - read_iteration_counter(eng): tolerant int read of engagement/iteration.
  - normalize_for_digest(text) / handoff_digest(eng): the canonical form and
    sha256 a verdict is bound to (see acceptance.check_handoff_digest).
  - run(cmd, cwd): subprocess wrapper with 30s timeout, returns (rc, stdout+stderr).
"""

from __future__ import annotations

import hashlib
import re
import subprocess
from pathlib import Path

# Entries (files or directory subtrees) permitted at the top level of an
# engagement/ directory. Anything else is "rogue" and rejected by check_whitelist.
WHITELIST = {
    # Files
    "criteria.md", "scope-sync.md", "plan.md",
    "validation-log.md", "deploy-log.md", "docs-diff.md",
    "handoff.md", "acceptance-log.md",
    "consilium-summary.md",  # tiered acceptance: aggregated adversary findings (M/L)
    "human-directive.md",    # human-as-supreme-judge: directive between consilium and director verdict
    "iteration",  # plain-text iteration counter (Tier 6.3)
    "engagement-reflections.md",  # per-engagement reflection layer (M/L)
    "events.jsonl",          # append-only event ledger (lib/ledger.py)
    # Directories (subtree allowed under each)
    "specs", "tasks", "brand", "design-system", "ui",
    "executor-reports", "screens", "traces",
    "validation-outputs",  # JSON proof-of-run for each validator + adversary role
    "codex-outputs",       # Codex MCP bridge: PNGs/SVGs generated by mcp__codex__codex tool calls
    "copy", "reports", "banners", "keywords",  # marketing artefact deliverables (Workflow artefact mode)
}

# Frontmatter keys required in every criteria.md. `protocol_version` is OPTIONAL.
CRITERIA_FRONTMATTER_REQUIRED = {
    "engagement", "domain", "size", "ux_heavy", "tools_required",
}


def read_criteria_meta(eng: Path) -> dict:
    """Read size, ux_heavy, domain, engagement from criteria.md frontmatter.

    Returns {} on missing criteria.md or unparseable frontmatter — caller
    must defensively default size to "M" and ux_heavy to "false" in that case.
    """
    crit = eng / "criteria.md"
    if not crit.exists():
        return {}
    text = crit.read_text(encoding="utf-8")
    fm = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not fm:
        return {}
    body = fm.group(1)
    meta = {}
    for k in ["size", "ux_heavy", "domain", "engagement"]:
        m = re.search(rf"^{k}\s*:\s*(\S+)", body, re.MULTILINE)
        if m:
            meta[k] = m.group(1).strip().strip('"').strip("'")
    return meta


def read_iteration_counter(eng: Path) -> int | None:
    """Tolerant read of engagement/iteration. None when absent or unparseable.

    The file is sometimes written UTF-8-WITH-BOM, and str.strip() does NOT
    remove U+FEFF (it is not whitespace), so a plain "utf-8" read makes int()
    raise on a BOM-prefixed "1" — the false-failure recorded in the
    skill-evolution log for 2026-06-04. utf-8-sig drops a leading BOM on
    decode; the extra lstrip covers a stray one.

    iteration.py keeps an equivalent private reader for its own three checks;
    this one exists so a new check need not reach into that module's privates
    and re-learn the same lesson.
    """
    counter = eng / "iteration"
    if not counter.exists():
        return None
    try:
        raw = counter.read_text(encoding="utf-8-sig").strip().lstrip("﻿").strip()
        return int(raw)
    except Exception:
        return None


def normalize_for_digest(text: str) -> str:
    """Canonical form a handoff digest is computed over.

    Deliberately narrow: whitespace SHAPE only, never content. A digest that
    quietly ignored content would defeat its own purpose.

      - CRLF / CR collapse to LF, so a Windows-side rewrite is not a change
      - trailing whitespace stripped per line
      - leading and trailing blank lines stripped
      - exactly one trailing newline, so "ends with a newline" is not a change

    Everything else, timestamps included, counts as content. A regenerated
    handoff therefore gets a new digest, which is intended: regeneration is
    rework, and rework is exactly what must invalidate a verdict.
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [ln.rstrip() for ln in text.split("\n")]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def handoff_digest(eng: Path) -> str | None:
    """sha256 over the normalized handoff.md. None when handoff.md is absent."""
    handoff = eng / "handoff.md"
    if not handoff.exists():
        return None
    raw = handoff.read_text(encoding="utf-8", errors="replace")
    return hashlib.sha256(normalize_for_digest(raw).encode("utf-8")).hexdigest()


def run(cmd: list[str], cwd: Path | None = None) -> tuple[int, str]:
    """Run subprocess with 30s timeout, return (returncode, stdout+stderr).

    Exit 99 on Python-level error (timeout, file-not-found, etc).
    """
    try:
        r = subprocess.run(cmd, capture_output=True, text=True,
                           encoding="utf-8", errors="replace",
                           timeout=30, cwd=cwd)
        return r.returncode, (r.stdout + r.stderr).strip()
    except Exception as e:
        return 99, f"error: {e}"
