"""Shared constants and utilities for pre-handoff checks.

Constants split rule:
  - Things used by *multiple* topic-modules live here (WHITELIST,
    CRITERIA_FRONTMATTER_REQUIRED).
  - Things used by exactly one topic module live in that module
    (REQUIRED_HANDOFF_SECTIONS -> handoff.py, OPTIONAL_VALIDATORS -> validators.py, ...).
  - TIER_CHECKS stays in handoff-precheck.py (dispatch concern, not check concern).

Utilities here:
  - read_criteria_meta(eng): read size / ux_heavy / domain / engagement from
    criteria.md frontmatter. Returns {} on missing or unparseable.
  - run(cmd, cwd): subprocess wrapper with 30s timeout, returns (rc, stdout+stderr).
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

# Entries (files or directory subtrees) permitted at the top level of an
# engagement/ directory. Anything else is "rogue" and rejected by check_whitelist.
WHITELIST = {
    # Files
    "criteria.md", "scope-sync.md", "plan.md",
    "validation-log.md", "deploy-log.md", "docs-diff.md",
    "handoff.md", "acceptance-log.md",
    "consilium-summary.md",  # tiered acceptance: aggregated adversary findings (M/L)
    "human-directive.md",    # human-as-supreme-judge: directive between consilium and director verdict
    "iteration",  # plain-text iteration counter
    "engagement-reflections.md",  # per-engagement reflection layer (M/L)
    "events.jsonl",          # append-only event ledger (lib/ledger.py)
    # Directories (subtree allowed under each)
    "specs", "tasks", "brand", "design-system", "ui",
    "executor-reports", "screens", "traces",
    "validation-outputs",  # JSON proof-of-run for each validator + adversary role
    "codex-outputs",       # Codex MCP bridge: PNGs/SVGs generated by mcp__codex__codex tool calls
}

# Frontmatter keys required in every criteria.md. `protocol_version` is OPTIONAL.
CRITERIA_FRONTMATTER_REQUIRED = {
    "engagement", "domain", "size", "ux_heavy", "tools_required",
}


def read_criteria_meta(eng: Path) -> dict:
    """Read size, ux_heavy, domain, engagement from criteria.md frontmatter.

    Returns {} on missing criteria.md or unparseable frontmatter — caller
    must defensively default size to "M" and ux_heavy to "false" in that case.
    """
    crit = eng / "criteria.md"
    if not crit.exists():
        return {}
    text = crit.read_text(encoding="utf-8")
    fm = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not fm:
        return {}
    body = fm.group(1)
    meta = {}
    for k in ["size", "ux_heavy", "domain", "engagement"]:
        m = re.search(rf"^{k}\s*:\s*(\S+)", body, re.MULTILINE)
        if m:
            meta[k] = m.group(1).strip().strip('"').strip("'")
    return meta


def run(cmd: list[str], cwd: Path | None = None) -> tuple[int, str]:
    """Run subprocess with 30s timeout, return (returncode, stdout+stderr).

    Exit 99 on Python-level error (timeout, file-not-found, etc).
    """
    try:
        r = subprocess.run(cmd, capture_output=True, text=True,
                           encoding="utf-8", errors="replace",
                           timeout=30, cwd=cwd)
        return r.returncode, (r.stdout + r.stderr).strip()
    except Exception as e:
        return 99, f"error: {e}"
